return {
  {
    "stevearc/conform.nvim",
    opts = {
      notify_on_error = true,
      formatters_by_ft = {
        css = { "prettierd" },
        fish = { "fish_indent" },
        go = { "gofmt" },
        html = { "prettierd", "rustywind" },
        htmldjango = { "djlint", "rustywind" },
        javascript = { "biome" },
        javascriptreact = { "biome" },
        json = { "biome" },
        jsonc = { "biome" },
        just = { "just" },
        -- lua = { "stylua" },
        markdown = { "prettierd" },
        nix = { "alejandra" },
        php = { "pint" },
        scss = { "prettierd" },
        sh = { "shfmt" },
        sql = { "sqlfluff" },
        toml = { "taplo" },
        typescript = { "biome" },
        ["typescript.tsx"] = { "biome" },
        typescriptreact = { "biome" },
        xml = { "xmlformat" },
        yaml = { "yamlfix" },
      },
      formatters = {
        sqlfluff = { args = { "format", "--dialect=postgres", "-" } },
        -- sql_formatter = { prepend_args = { "--language=postgresql" } },
        -- sqlfmt = { prepend_args = { "-l", "120" } },
      },
    },
  },
}
