return {
	"stevearc/conform.nvim",
	dependencies = { "mason.nvim" },
	opts = {
		default_format_opts = {
			lsp_format = "fallback",
		},
		format_on_save = {
			timeout_ms = 500,
		},
		notify_on_error = true,
		formatters_by_ft = {
			css = { "prettierd" },
			dockerfile = { "hadolint" },
			fish = { "fish_indent" },
			go = { "gofmt" },
			html = { "prettierd" },
			htmldjango = { "djlint" },
			jinja = { "djlint" },
			just = { "just" },
			lua = { "stylua" },
			markdown = { "markdownlint-cli2" },
			nix = { "alejandra" },
			-- php = { "pint" },
			scss = { "prettierd" },
			sh = { "shfmt" },
			sql = { "sqlfluff" },
			toml = { "taplo" },
			javascript = { "biome-check" },
			javascriptreact = { "biome-check" },
			json = { "biome-check" },
			jsonc = { "biome-check" },
			ruby = { "rubocop" },
			eruby = { "erb_format" },
			terraform = { "terraform_fmt" },
			tf = { "terraform_fmt" },
			typescript = { "biome-check" },
			["typescript.tsx"] = { "biome-check" },
			typescriptreact = { "biome-check" },
			xml = { "xmlformat" },
			yaml = { "yamlfix" },
		},
		formatters = {
			injected = { options = { ignore_errors = true } },
			sqlfluff = { args = { "format", "--dialect=postgres", "-" } },
		},
	},
}
