theme = "gruvbox"

[editor]
true-color = true
color-modes = true
middle-click-paste = false
cursorline = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
S-ret = "@:"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"
# # remap all movements to h-t-n-s (dvorak)

# t = "move_line_down" # old 'till_char'
# n = "move_line_up" # old 'search_next'
# s = "move_char_right" # old 'select_regex'
# # remap old movement keys
# l = "find_till_char"
# L = "till_prev_char"
# j = "select_regex"
# J = "split_selection" # old 'join_lines'
# T = "join_selections"
# k = "search_next"
# K = "search_prev"
# N = "keep_selections"
# A-N = "remove_selections"

# [keys.select]
# t = "move_line_down" # old 'till_char'
# n = "move_line_up" # old 'search_next'
# s = "move_char_right" # old 'select_regex'
# # remap old movement keys
# l = "find_till_char"
# L = "till_prev_char"
# j = "select_regex"
# J = "split_selection" # old 'join_lines'
# T = "join_selections"
# k = "search_next"
# K = "search_prev"
# N = "keep_selections"
# A-N = "remove_selections"


# # remap goto mode
# [keys.normal.g]
# s = "goto_line_end"
# l = "goto_first_nonwhitespace"

# #remap window movement
# [keys.normal."C-w"]
# t = "jump_view_down"
# C-t = "jump_view_down"
# T = "swap_view_down"
# n = "jump_view_up"
# C-n = "jump_view_up"
# N = "swap_view_up"
# s = "jump_view_right"
# C-s = "jump_view_right"
# S = "swap_view_right"
# z = "hsplit"
# C-z = "hsplit"
